### ISSUE TITLE
Semantic sorting

### ISSUE THREAD

**Issue by tbeu** [impact/search#13]
MSL 3.2.1+build.2 is sorted before 3.2.1+build.3 which should be the other way round.

**Comment by xogeny** [comment]
This was fixed in 30e48844f983f1ecccb2f27d4af9d5e492c17078 and has been published now.  Try it and let me know if you see any issues now.

**Comment by tbeu** [comment]
Still not fixed. If version contains a "+" it is sorted the wrong way.

**Comment by xogeny** [comment]
I see what you mean.  However, this is actually the correct behavior.  From [semver.org](http://semver.org/):

  > Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. **Build metadata SHOULD be ignored when determining version precedence**. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

**Comment by tbeu** [comment]
Thanks for pointing this out.

**Comment by dietmarw** [comment]
I got caught by this too in the past since semver.org actually *changed* that part about how build information should be interpreted.
